### ISSUE TITLE
Pause on lost focus option

### ISSUE THREAD

**Issue by Luke18033** [codieradical/MineOnline#148]
Add an option for pausing on lost focus in older versions. When disabled, alt-tabbing out of Minecraft while unpaused would stop pointer tracking, but would not automatically open the menu or pause the game.

In newer versions with `F3+P`, this would simply auto-set that value in `options.txt` before launching.

**Comment by codieradical** [comment]
This is reasonably straightforward to do:

Patch Display.isActive() to always return true.
Detect focus and focus loss, grab and ungrab the mouse.
Will probably include this in 3.3.0

**Comment by codieradical** [comment]
pauseOnLostFocus
