### ISSUE TITLE
Explosion sounds are wrong in some versions.

### ISSUE THREAD

**Issue by Luke18033** [codieradical/MineOnline#149]
The game seems to randomize between the old sound and the modern sound, instead of only playing the former. Experienced in Alpha 1.2.6, but it likely applies to all pre-1.0 versions.

**Comment by codieradical** [comment]
Good catch.
a1.2.6 is using a sound pack I found for b1.3_01, as that's the closest I've got.
The next pack (which applies to versions after b1.3_01 is b1.4_01, so it's possible that my b1.3_01 pack is wrong.
I'll have a look.

**Comment by codieradical** [comment]
b1.7.3 is correct...

**Comment by codieradical** [comment]
I gave a1.2.6 a go, I've not experienced it so far, I'll dig through the files to be sure.

**Comment by codieradical** [comment]
To be reopened if reproduced.
