### ISSUE TITLE
Java 14 Linux Compatibility: Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by a8underscore** [codieradical/MineOnline#150]
when launching the jar i get 
`Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!`
the program doesnt run past this point

my system info
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.9.1-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-5650U CPU @ 2.20GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 6000

my java info: 
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12)
OpenJDK 64-Bit Server VM (build 14.0.2+12, mixed mode)

**Comment by codieradical** [comment]
Please try Java 8, I believe there are some compatibility issues with newer versions on mac at the moment.

**Comment by a8underscore** [comment]
I am not on macOS i am on linux

**Comment by codieradical** [comment]
My bad! Misread

**Comment by codieradical** [comment]
Only one report and significant code changes have been made since. Open if this happens again.

**Comment by a8underscore** [comment]
this issue still persists on latest version
