### ISSUE TITLE
Custom cape textures applied wrong in launcher skin preview

### ISSUE THREAD

**Issue by Luke18033** [codieradical/MineOnline#168]
The back texture is flipped, and both sides use the same texture (left). It appears fine in-game and on the MinecraftCapes website (right).
![image](https://user-images.githubusercontent.com/19228201/98329242-9f288180-1fac-11eb-851e-2eee21c12245.png)
This may be related to having a custom elytra in the texture, I haven't tested a cape without one.

**Comment by Luke18033** [comment]
It also renders transparency in capes, which doesn't seem to be supported by the actual game. (Because why would they need it? No official cape is transparent, and they didn't intend to support custom ones.)

**Comment by codieradical** [comment]
Since the player renderer has been removed I'm going to close this.
If/when we reimplement, we'll get it right :p
