### ISSUE TITLE
Support adding private servers to the server list

### ISSUE THREAD

**Issue by Luke18033** [codieradical/MineOnline#186]
Currently joining a private server requires entering the IP into Direct Connect, with no option to save it. The server list should have Add/Edit/Remove Server buttons like the in-game server list, which can be used to add a specific server with a custom name. These servers would be displayed at the top of the list (possibly with some sort of divider below) and could be reorganized. Public servers should also be able to be "pinned" or "bookmarked", moving them into this top section and making them visible even when offline.

This would be useful for versions of the game before Beta 1.8, which don't include an in-game server list.

**Comment by codieradical** [comment]
If anyone wants to jump on this, try to keep it similar to the official server list's design.
The servers should be stored in JSON.
Also, when it comes to selecting the server version, the version list can be adapted to list servers.

![image](https://user-images.githubusercontent.com/11706994/100102307-50f3f900-2e5b-11eb-88ca-7e63965223fe.png)

**Comment by Luke18033** [comment]
Instead of having a divider between custom servers and public servers, perhaps add a "pinned" icon that would appear on the server.
Here's a quick mockup I made by replacing the featured server icon:
![image](https://user-images.githubusercontent.com/19228201/100170466-9e339300-2e7a-11eb-8133-32cbf8524a52.png)
The pin icon and online mode icons would be able to both appear. I'm not sure how useful it would be to know if a pinned server is also featured, so that icon can probably be hidden for pinned servers.
