### ISSUE TITLE
MineOnline servers API don't work

### ISSUE THREAD

**Issue by Strongleong** [codieradical/MineOnline#269]
Because hosting server with MineOnline don't work on Debian I tried write simple python script. I run it, and I get 500 response. I thought it was because of my script so I tested requests with RESTCilent. Same results.
My request:
`{
  "name": (server name),
  "ip": (server adders),
  "port": "25565",
  "onlinemode": "false",
  "md5": "46FE20AB3BFE3F574E7C758B5A25B9C9"
  "whitelisted": "true",
  "maxUsers": "10",
  "players": []
}`

**Comment by codieradical** [comment]
change "maxUsers" to "max".

**Comment by codieradical** [comment]
I've updated the webpage to reflect the correction, it'll change whenever I reboot the API next.
