### ISSUE TITLE
Buttons don't sound on linux

### ISSUE THREAD

**Issue by Strongleong** [codieradical/MineOnline#272]

**Comment by codieradical** [comment]
We test on linux and this hasn't come up yet. Needs reproducing.

**Comment by Strongleong** [comment]
Here is proof [video](https://youtu.be/6kwZcMfrhGY)

**Comment by codieradical** [comment]
I'm not going to fix this as this is a minor issue that affects a small subset of users, so far this is the first and only report. I also can't eliminate user error and reproduce as I don't have time to recreate your setup. If anyone else wants to fix this let me know and I'll reopen.
