### ISSUE TITLE
Bizarre graphical glitch when launcher used on MacOS

### ISSUE THREAD

**Issue by theconstanzamethod** [codieradical/MineOnline#278]
Hi there, I booted the .jar file provided on a 2011 13" Macbook Pro, which presnted a strange graphical glitch pictured below. 

I've used this launcher as an .exe file under windows on a separate machine with no issues, maybe this owes to the fact this machine uses intergrated graphics if that points you in the right direction? The integrated graphics on Sandy Bridge CPUs is famously awful from what I've heard. I'm running 10.13 btw, I know they changed the way MacOS handles graphics for 10.14 if you can't replicate this. 

Thanks if you can help, I really really like this launcher and that's why it frustrates me I can't use it on my laptop :)

![Screen Shot 2021-03-13 at 4 49 32 pm](https://user-images.githubusercontent.com/80565799/111020943-66e2f500-841d-11eb-950a-819677d162a1.png)

**Comment by codieradical** [comment]
What version of Java and MacOS are you using?

**Comment by theconstanzamethod** [comment]
10.13 and the Java version is 8 version 271
