### ISSUE TITLE
the launcher calls rd-20090515 rd161348

### ISSUE THREAD

**Issue by whitebeartigtig** [codieradical/MineOnline#84]
![Capture](https://user-images.githubusercontent.com/63053458/86631876-90ae6700-bfc6-11ea-8146-d3600cd5e797.PNG)

**Comment by codieradical** [comment]
According to omniarchive, rd-20090515 is identical to rd-161348.

**Comment by codieradical** [comment]
I double checked with the official launcher, these jars are the same.

https://launchermeta.mojang.com/v1/packages/1bcd01f323df5c5092e9f0967b3d310d5bc0013a/rd-20090515.json
https://launchermeta.mojang.com/v1/packages/a937d17cca60af0a7d45d04b49a849af16b08a28/rd-161348.json

I also downloaded both versions in the launcher and checked the hashes.
![image](https://user-images.githubusercontent.com/11706994/86634017-47abe200-bfc9-11ea-9374-ba451c69c0fa.png)
