### ISSUE TITLE
black screen on macos catalina

### ISSUE THREAD

**Issue by arceuss** [codieradical/MineOnline#89]
tried adoptopenjdk8 and oracle jdk 8
seen here
https://cdn.discordapp.com/attachments/715617140538998858/736267512274223144/Screenshot_2020-07-24_at_18.04.07.png

**Comment by codieradical** [comment]
I'm using adoptopenjdk8 1.8.0_232
![image](https://user-images.githubusercontent.com/11706994/88419018-56bdcd00-cddc-11ea-9b1c-e3992c55d57a.png)


What device are you using?

**Comment by arceuss** [comment]
https://media.discordapp.net/attachments/715617140538998858/736272981315158046/Screenshot_2020-07-24_at_18.25.53.png

**Comment by arceuss** [comment]
and latest version of adoptopenjdk

**Comment by codieradical** [comment]
Interesting, if I had to guess I'd say it's shader related, our hardware isn't significantly different.
Could you launch from terminal and paste the log please? Assuming there's an output.

**Comment by arceuss** [comment]
nvm i used the same version and jdk and now it works
